name : Test

on:
  pull_request: 
    branches:
      - try2

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run : echo 'Hello peeps from the pipeline!'

  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and clone repo
        uses: actions/checkout@v3
      - name: Install dependenies
        run: npm install
      - name: Test utils
        run: npm run test-utils